### ISSUE TITLE
Controlar la "profundidad" de las entidades (o usar Layers)

### ISSUE THREAD

**Issue by HakS** [RglMrn/La-Vaca-Lechera#27]
Algo que he notado es que la ultima entidad creada se coloca debajo de cualquier entidad creada antes, a traves de esa caracteristica se podria ordenar la "profundidad" de las entidades, pero lo ideal seria que cada entidad tenga un atributo Profundidad, el cual permita trabajar de manera ordenada las entidades, lo ideal seria enumerarlas.

**Comment by RglMrn** [comment]
Estuve viendo y el hecho de que nuestras funciones de dibujar pidan como parámetro un contexto de canvas significa que nosotros podemos pasarle el canvas que queramos (no tiene que ser un solo canvas) y podríamos manjerar los layers por medio de diferentes capas de canvas

**Comment by RglMrn** [comment]
El manejo de profundidades se está manejando con el atributo z de cada entidad, pero existe un pequeño problema con la sombra. Por lo que cerraré este issue y abriré uno nuevo para el problema con la sombra.
