### ISSUE TITLE
INDEX_SIZE_ERR: DOM Exception 1

### ISSUE THREAD

**Issue by alexishevia** [RglMrn/La-Vaca-Lechera#35]
En el commit 89977a5c3b3e183e77ccc25c357620092a8f8578 (Añadi el super pollo de Zealotscout!!!...) se introdujo un bug que crashea Google Chrome. La consola tira este error:

Uncaught Error: INDEX_SIZE_ERR: DOM Exception 1
animation.js:25

Por lo cual estoy casi seguro que hay un problema en la animacion del pollo.

**Comment by RglMrn** [comment]
Yo puedo abrir el último commit en google chrome. El bug persiste para ti?

**Comment by RglMrn** [comment]
Probé ese mismo commit en google chrome y no me crashe =/.

**Comment by alexishevia** [comment]
Jajaj.. a mi sí se me crashea.. es justo cuando la animación del pollo termina. Ahora en la tarde me pongo a ver el código para ver qué está pasando.

**Comment by RglMrn** [comment]
Voy a ver si me descargo Chromium para probarlo ahí

**Comment by alexishevia** [comment]
Creo que por aquí va el asunto: 
http://blog.ryanrampersad.com/2010/06/04/index_size_err-dom-exception-1-html-canvas/

**Comment by RglMrn** [comment]
Lo acabo de probar en Chromium 12.0.742.112 y Google Chrome 14.0.835.202 y en ambos funciona bien. En base a lo que dices de valores negativos tengo una idea de que es lo que puede estar pasando pero no logro replicar el bug
