### ISSUE TITLE
Chorros caen a la vez

### ISSUE THREAD

**Issue by alexishevia** [RglMrn/La-Vaca-Lechera#4]
Parece que hay momentos en que más de un chorro cae a la vez. Hay que investigar por qué y arreglarlo.

**Comment by RglMrn** [comment]
La razón por la cual caen a la vez es porque la lógica que se emplea (en vaca.elegirDisparo) no toma en consideración el tiempo que pasa la vaca moviéndose/disparando. Hay que hacer una reestructuración para corregir el problema.
